### ISSUE TITLE
Support use of formulas in property, units, precision, etc.

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#100]
In general, formulas can be used to compute the value of any attribute in a YAML file. For example:
```
# OECD mapping
statementMapping:
  region: 
    - range: D6:K12
      skip_cell:
        - =value[$col, $row] == " .."
  template:
    # The next line should wikify the extracted country
    #item: '=get_item(regex(value[B, 2], "profile: (.*) \d{4}", 1))' 
    item: Q31 # Belgium
    property: =item[B, $row]
    value: =replace(value[$col, $row], "[^\d.-]", "")
    unit: =item[C, $row]
    qualifier:
      - property: P585 #point in time
        value: =value[$col, 4]
        calendar: Q1985727
        precision: year
        time_zone: 0
        format: "%Y"
    reference: 
      - property: P246 # stated in
        value: Q41550 # OECD
      - property: P2006010001 # Datamart dataset id
        value: Q2006050001 # OECD dataset
```

In this example, formulas are used in `property` and `unit`, but in general formulas could be used anywhere.
