### ISSUE TITLE
References should be lists of lists

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#102]
References are currently implemented the same way as qualifiers. However, references should be list of lists as in
```
# OECD mapping
statementMapping:
  region: 
    - range: D6:K12
      skip_cell:
        - =value[$col, $row] == " .."
  template:
    # The next line should wikify the extracted country
    #item: '=get_item(regex(value[B, 2], "profile: (.*) \d{4}", 1))' 
    item: Q31 # Belgium
    property: =item[B, $row]
    value: =replace(value[$col, $row], "[^\d.-]", "")
    reference: 
      - - property: P246 # stated in
          value: Q41550 # OECD
        - property: P2006010001 # Datamart dataset id
          value: Q2006050001 # OECD dataset
      - - property: P246 # stated in
          value: Q123456 
        - property: PP1234567 # Datamart dataset id
          value: "hi there"
```
