### ISSUE TITLE
Apply YAML for indicator files takes a really long time

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#11]
Applying the YAML file to this CSV takes a really long time:
[DT.ODA.ODAT.GI.ZS.csv.zip](https://github.com/usc-isi-i2/t2wml/files/3360637/DT.ODA.ODAT.GI.ZS.csv.zip)

Is it taking a long time in the server or in the browser?

```
statementMapping:
  region:
    - left: D
      right: BL
      top: 5
      bottom: 269
  template:
    item: item(A/$row)
    property: item(D/$row)
    value: value($col/$row)
    #unit: # need to define the units
    qualifier:
      - property: P585
        value: value($col/4)
        calendar: Q1985727
        precision: year
        time_zone: 0
```
