### ISSUE TITLE
make get_item case-insensitive

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#112]
requested by @kyao 
  
```
template:
    item: =item[A, $row]
    property: '=get_item(regex(upper(value[$col, 3]), "(.*) \d{4}", 1),"property")'
    value: =value[$col, $row]
```
I get a BAD REQUEST error, If I take out upper then the BAD REQUEST error goes away
