### ISSUE TITLE
Iterator variable

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#115]
When applying the yaml below to the attached excel spreadsheet, T2WML is reporting `ERRORS while applying yaml:` with an empty object in the browser console. I want to all skip columns  except J through AD.

```
statementMapping:
  region:
    - left: =B
      right: =AD
      top: 8
      bottom: =$end
      skip_column:
        - =value[$col-$n,2] != "variable"
  template:
    item: =value[$row,B]
    property: P1114
    value: =value[$col,$row]
    qualifier:
      - property: P585
        value: =value[C,$row]
```

[aid worker security_incidents2020-06-22-annotated.xlsx](https://github.com/usc-isi-i2/t2wml/files/4900086/aid.worker.security_incidents2020-06-22-annotated.xlsx)
