### ISSUE TITLE
yaml parser not working properly

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/t2wml#118]
On the old version(2.0.0a16), this parser works properly to parse all data
```
# OECD mapping
statementMapping:
  region: 
    - left: D
      right: K
      top: 6
      # find the bottom of the data
      bottom: =value[C:D, $top+$n] == "" -> $top+$n-1 
      #bottom: 6
      skip_cell:
        - =value[$col, $row] == " .."
        - =contains(value[$col, $row], "c") 
```
![image](https://user-images.githubusercontent.com/25087508/87367267-55b0b400-c52f-11ea-8840-6f8010e73b60.png)

However, in the new version (2.0.0a18), this parser not work and only part of the rows were parsed
![image](https://user-images.githubusercontent.com/25087508/87367347-91e41480-c52f-11ea-9187-41d3de5983af.png)
