### ISSUE TITLE
Error report in t2wml-api

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#135]
Please change the error report to the following format ,

```
{
  "{cell_id}": {
    "technical_error": "line number {n} in the yaml file. {actual line from the yaml file}. Any other technical details",
    "row": "{row number}",
    "column": "{column number}",
    "layman_error": "the {value} in the cell could not be wikified or {value} is not a number or {value} is not a valid date"
  }
}
```

For example, if we have this line in yaml `value: =item[F, $row, "admin1"]` and row 5 in column F is not present in wikifier, then the error could look like this

```
{
  "F5": {
    "technical_error": "line number 13 in the yaml file. line: "value: =item[F, $row, "admin1"]",. String `Lost Angeles` is not present in the wikifier,
    "row": "5",
    "column": "5",
    "layman_error": "String `Lost Angeles` could not be wikified. Please check the spelling"
  }
}

```

Another example, lets say we have a yaml file which has the following qualifier section
```
qualifier:
    - calendar: Q1985727
      format: '%Y-%m-%d'
      precision: day
      property: P585
      time_zone: 0
      value: =value[B, $row]
```

```
{
  "B35": {
    "technical_error": "line number 28 in the yaml file. line: "value: =value[B, $row]",
    "row": "35",
    "column": "1",
    "layman_error": "The value 2019-34-12 is not a valid date." 
  }
}
```

Please let us know the feasibility of this feature
