### ISSUE TITLE
lat/lon coordinate

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#138]
Getting the following error while generating kgtk edge file. Error occurs in interactive Windows executable and in version 19.

`ValueError: dict contains fields not in fieldnames: ' node2;kgtk:globe'`

Data is:
```
country,longitude,latitude,value
Ethiopia,40,9,100
USA,41,10,101
```

Yaml is:
```
statementMapping:
  region:
    - left: D
      right: D
      top: 2
      bottom: 3
  template:
    item: =item[A, $row]
    property: P1000
    value: =value[D, $row]
    qualifier:
      - property: P625
        longitude: =value[B, $row]
        latitude: =value[C, $row]
        globe: wgs84
```

Wikifier is:
```
column,row,value,context,item
,,Ethiopia,,Q115
,,USA,,Q30
```
