### ISSUE TITLE
boolean equation not working for "unit"

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#153]
The file required to reproduce this issue is attached

The yaml file is as follows,

```
statementMapping:
  region:
  - bottom: 106
    left: E
    right: R
    top: 14
    # Have to add the following skip_cells
    skip_cells: 
      - =contains(value[$col, $row], '*')
      - =contains(value[$col, $row], '‐')
      - =contains(value[$col, $row], '-')
  template:
    item: =item[B, $row, "admin1"]
    property: =item[$col, 13, "property"]
    qualifier:
    - calendar: Q1985727
      format: '%Y'
      property: P585
      time_zone: 0
      #value: =value[D, $row]
      value: =regex(value[D, $row], "(....)/")
    - property: P2006020004
      value: QEth-fertilizer
    - property: P2006190001
      value: =item[B, $row, "admin1"]
    - property: P131
      value: =item[B, $row, "admin1"]
    unit: =value[$col,6] != "" -> value[$col, 6]
    value: =value[$col, $row]
```
[t2wml-training.zip](https://github.com/usc-isi-i2/t2wml/files/5060864/t2wml-training.zip)

The relevant line in line number 28 in the yaml. We expect the cells to not turn orange but somehow the boolean expression is not working.
