### ISSUE TITLE
Incorrect date time parsing 

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#155]
Again, use the attached zip file to reproduce
[t2wml-training.zip](https://github.com/usc-isi-i2/t2wml/files/5060895/t2wml-training.zip)

The yaml file as as follows,

```
statementMapping:
  region:
  - bottom: 106
    left: E
    right: R
    top: 14
    # Have to add the following skip_cells
    skip_cells: 
      - =contains(value[$col, $row], '*')
      - =contains(value[$col, $row], '‐')
      - =contains(value[$col, $row], '-')
  template:
    item: =item[B, $row, "admin1"]
    property: =item[$col, 13, "property"]
    qualifier:
    - calendar: Q1985727
      format: '%Y'
      property: P585
      time_zone: 0
      value: =value[D, $row]
    - property: P2006020004
      value: QEth-fertilizer
    - property: P2006190001
      value: =item[B, $row, "admin1"]
    - property: P131
      value: =item[B, $row, "admin1"]
    unit: =value[$col,6] != "" -> value[$col, 6]
    value: =value[$col, $row]
```

The issue is the format for date qualifier is `%Y` which should only match 4 digit years. The data is in format 2004/05 which really means the year 2004/2005, but it is being parsed as 2004, May which is incorrect.

We have to change the value to `value: =regex(value[D, $row], "(....)/")` to actually make it do what we want. The current yaml should fail to parse the date
