### ISSUE TITLE
T2WML is ignoring the date format in the yaml

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#169]
Yaml 

```
statementMapping:
  region:
  - bottom: 46
    left: F
    right: H
    top: 8
  template:
    item: =item[D, $row, "main subject"]
    property: =item[$col, 7, "property"]
    qualifier:
    - calendar: Q1985727
      format: '%d'
      property: P585
      time_zone: 0
      value: =value[E, $row]
    - property: P2006020004
      value: Qt2wml_test_03
    - property: P2006190003
      value: =item[B, $row, "admin3"]
    - property: P2006190002
      value: =item[C, $row, "admin2"]
    - property: P131
      value: =item[B, $row, "admin3"] or item[C, $row, "admin2"]
    value: =value[$col, $row]

```

1. Upload the attached file, and this yaml file.
2. Time is auto detected, which is a super nice feature
3. But when I try to change the time format to `%d` , as in the yaml,  nothing happens. I should be able to change the format

[flood_2008_annotated_truncated.xlsx.zip](https://github.com/usc-isi-i2/t2wml/files/5087844/flood_2008_annotated_truncated.xlsx.zip)
