### ISSUE TITLE
Add datetime parser

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/t2wml#46]
I updated ETK to support parsing datetime based on date extractor. In t2wml, please allow user to define "format" of datetime. Then use `etk.wikidata.utils.parse_datetime_string` (examples: https://github.com/usc-isi-i2/etk/blob/development/etk/unit_tests/test_wiki_utils.py#L6) to convert datetime to iso format. The return of this function will be a tuple `(iso format datetime string, precision)`, then you can pass values in tuple to `etk.wikidata.vallue.TimeValue`.

**Comment by bhatiadivij** [comment]
I integrated the `etk.wikidata.utils.parse_datetime_string` function but it turns out that it doesn't work on some data files. 

Debugging Steps Performed:
1. Debugged the variables being passed in realtime.
2. I tried interchanging data file formats but it didn't help.

To reproduce the same issue perform the following steps:
1. Checkout branch `feature/datetime_parser`
2. Run T2WML server and visit `http://localhost:5000`
3. Try downloading the .`ttl` using the files attached.
4. The error occurs here: https://github.com/usc-isi-i2/t2wml/blob/433a4d8c61fff4e1f9151307f24bd5115fcc7266/Code/handler.py#L297
[Files.zip](https://github.com/usc-isi-i2/t2wml/files/3737028/Files.zip)

**Comment by szeke** [comment]
The YAML file should be:
```
statementMapping:
  region:
    - left: D
      right: BJ
      top: 5
      bottom: 270
  template:
    item: item(A/$row)
    property: item(D/$row)
    value: value($col/$row)
    # unit: item(H/$row)
    qualifier:
      - property: P585
        value: value($col/5)
        format: "%Y"
        calendar: Q1985727
        precision: year
        time_zone: 0
      - property: P248 # stated in
        value: Q21540096 # World Bank database
      - property: P275 # license
        value: Q20007257 # Creative Commons Attribution 4.0 International
```

After adding the `format` attribute the TTL generation works fine.

However, if there is no `format` keyword, it fails silently, no output and no error message.
