### ISSUE TITLE
Internal server error on Ethiopia population data

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#57]
I am getting INTERNAL SERVER error on a T2WML that looks correct. Files attached. Trying to apply to `tabula-UNDPEUE_WEREDA2000-4.csv`, YAML file is in the zip file.

[tabula-UNDPEUE_WEREDA2000-3.zip](https://github.com/usc-isi-i2/t2wml/files/3899940/tabula-UNDPEUE_WEREDA2000-3.zip)

**Comment by bhatiadivij** [comment]
There's an error in specifying the region. The `right` attribute should be `E` instead of `D`
@szeke

**Comment by szeke** [comment]
Ah, thanks, what I get for doing things late. 

I am stuck on another problem. I want to define one YAML file that works for all the files in the folder, `tabula-UNDPEUE_WEREDA2000-0.csv`, to `-14.csv`. The problem is that in column D, where the data is, the data does not always start in the same row, or ends in the same row. I got the `bottom` to work correctly, but can't get the top to work. I want the top to be the row after `C = "Wereda"` as in

```
statementMapping:
  region:
    - left: C
      right: E
      top: value(C/$top+n) = "Wereda" -> $top+n+1
      bottom: value(C/$top+n) = "" -> $top+n 
      skip_row:
        - value(C/$row) = "Sub Total" 
  template:
    item: item(C/$row)
    property: P1082
    value: value($col/$row)
```

**Comment by bhatiadivij** [comment]
I don't think it is a good idea to specify `top` in terms of `top`. This problem can be easily solved if we specify `row 0` as the base row instead of `$top`.
Also, specifying `bottom: value(C/$top+n)` won't work as in some of the data files, the cell just below `C= "Wereda"` is empty which makes this condition true.
Following T2WML spec will work on all the files:

```
statementMapping:
  region:
    - left: C
      right: E
      top: value(C/0+n) = "Wereda" -> 0+n
      bottom: value(A:C/$top+n) = "" -> $top+n 
      skip_row:
        - value(C/$row) = "Sub Total" 
  template:
    item: item(C/$row)
    property: P1082
    value: value($col/$row)
```
