### ISSUE TITLE
Cannot put constants in value

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#8]
The `value` attribute should be an arbitrary expression, including a constant, for example, the following should be valid `value: 2012`, but causes an error:
```
    qualifier:
      - property: P585
        value: 2012
        calendar: Q1985727
        precision: year
        time_zone: 0 
```
