### ISSUE TITLE
Static value for `value` attribute raises an exception

### ISSUE THREAD

**Issue by bhatiadivij** [usc-isi-i2/t2wml#87]
When I try to give a static value to `value` attribute instead of a T2WML value expression, the system generates this exception:
```json
"error": {"errorCode": 500, "errorTitle": "Undefined Backend Error", "errorDescription": "not enough values to unpack (expected 3, got 1)"}
```
Here is an example T2WML spec (based on homicide data table-1a):
```yaml
statementMapping:
  region:
    - left: D
      right: F
      top: 4
      bottom: 9
  template:
    item: item[A, $row]
    property: P100024 # murder
    value: Q6030821
    #unit: D1002
    qualifier:
      - property: P585
        value: value[$col, 3]
        calendar: Q1985727
        precision: year
        time_zone: 0
        format: "%Y"
      - property: P6001 # applies to people
        value: item[C, $row]
      - property: P123 #source
        value: item[B, $row]
      - property: P1640 # curator
        value: Q6030821 # ISI
```

Both  `template->value` and `template->qualifier->value` raise exceptions.
