### ISSUE TITLE
value[A+n, 3] doesn't work

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#89]
I want to define a YAML file as follows so that the `left` is the first column that has the value `irrigated_land`:

```
# irrigated_land
statementMapping:
  region:
    - left: value[A+n, 3] == "irrigated_land" -> A+n
      right: CB
      top: 9
      bottom: $end
  template:
    item: item[B, $row]
    property: P1082
    value: value[$col, $row]
```

Looks like it works to have the `+n` expression with $left as in `value[$left+n,3]`

Source and wikifier files attached:

[2007-10-01_factbook-small.xlsx](https://github.com/usc-isi-i2/t2wml/files/4600802/2007-10-01_factbook-small.xlsx)

[wikifier.zip](https://github.com/usc-isi-i2/t2wml/files/4600805/wikifier.zip)
