### ISSUE TITLE
Output only contains the first green cell

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#91]
YAML:
```
# irrigated_land
statementMapping:
  region:
    - left: CB
      right: CB
      top: 9
      bottom: $end
  template:
    item: item[B, $row]
    property: P1082
    value: value[$col, $row]
```

Wikifier and source file same as in issue #89 

Output file contains world, but not Afghanistan

[a90c5b34ea55414d97e988065790982e.json.zip](https://github.com/usc-isi-i2/t2wml/files/4600886/a90c5b34ea55414d97e988065790982e.json.zip)
