### ISSUE TITLE
unit not part of output or download

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#92]
YAML:
```
# irrigated_land
statementMapping:
  region:
    - left: CB
      right: CB
      top: 9
      bottom: 26
  template:
    item: item[B, $row]
    property: P1082
    value: value[$col, $row]
    unit: Q712226 # sq km
```

The main problem is that the units are not part of the JSON, so they will not appear in the final output.

A secondary problem is that the units are not shown in the output on the screen, less important to fix, but would be nice. It should get the label of the Qnode for the units and put it next to the value.

data and wikifier same as in issue #89 

<img width="716" alt="image" src="https://user-images.githubusercontent.com/1074599/81437414-fa71d800-911f-11ea-878d-b358a35a81d7.png">
