### ISSUE TITLE
references not part of the system yet?

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#94]
YAML:
```
# irrigated_land
statementMapping:
  region:
    - left: CB
      right: CB
      top: 9
      bottom: 26
  template:
    item: item[B, $row]
    property: P1082
    value: value[$col, $row] 
    unit: Q712226 # sq km 
    qualifier:
      - property: P585
        value: value[CD, 9]
        calendar: Q1985727
        precision: year
        time_zone: 0
        format: "%Y"
    reference:
      - property: P246 # stated in
        value: Q11191 # The World Factbook
```
